@echo off
echo Iniciando o backend NestJS...
cd backend
echo Instalando dependencias (se necessario)...
npm install
echo.
echo Gerando o Prisma Client...
npx prisma generate
echo.
echo Aplicando migracoes do banco...
npx prisma migrate deploy
echo.
echo Iniciando o servidor...
npm run start:dev
